#:schema node_modules/wrangler/config-schema.json
name = "janwilmake_uithub_stars"
main = "src/main.ts"
compatibility_date = "2025-01-01"

assets = { directory = "./src/public" }
routes = [
  { pattern = "stars.forgithub.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "GITHUB_STARS_CACHE"
id = "797c84c684304eb5bce6c4c293078ca5"
